# Generated by Django 2.1.7 on 2019-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.CharField(max_length=40)),
                ('default', models.CharField(max_length=40)),
                ('negative', models.CharField(max_length=40)),
            ],
        ),
    ]
