# Generated by Django 2.1.7 on 2019-05-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190509_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysismodel',
            name='default',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sentimentanalysismodel',
            name='negative',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sentimentanalysismodel',
            name='positive',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sentimentanalysismodel',
            name='tweet_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='core.TweetSearch'),
        ),
        migrations.AlterField(
            model_name='tweetsearch',
            name='count_tweets',
            field=models.IntegerField(),
        ),
    ]
