# Generated by Django 2.1.7 on 2019-05-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20190509_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField()),
                ('default', models.IntegerField()),
                ('negative', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_was_made', models.DateTimeField(verbose_name='time made')),
                ('count_tweets', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sentimentanalysismodel',
            name='tweet_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='core.TweetSearch'),
        ),
    ]
