# Generated by Django 2.1.7 on 2019-05-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190509_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsearch',
            name='time_was_made',
            field=models.IntegerField(),
        ),
    ]
