# Generated by Django 2.1.7 on 2019-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190509_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsearch',
            name='tags',
            field=models.CharField(default='Nenhuma tag utilizada para pesquisa', max_length=100),
        ),
    ]
